[package]
name = "uniffi-fixture-ext-types-transitive"
edition = "2021"
version = "0.22.0"
license = "MPL-2.0"
publish = false

[package.metadata.uniffi.testing]
external-crates = [
    "uniffi-fixture-ext-types-sub-lib",
    "uniffi-fixture-ext-types-lib-one",
]

[lib]
crate-type = ["lib", "cdylib"]
name = "uniffi_ext_types_transitive"

[dependencies]
anyhow = "1"
uniffi = { workspace = true }
uniffi-fixture-ext-types-sub-lib = { path = "../sub-lib" }

[dev-dependencies]
uniffi = { workspace = true, features = ["bindgen-tests"] }

[features]
ffi-trace = ["uniffi/ffi-trace"]
